blog/urls.py
from django.urls import path
from blog.views import index as blog_index                           
from blog.views import InsertJuego, InsertDesarrollador, BuscarJuego
from blog.views import *

#URLS DE PROYECTO FINAL

urlpatterns = [
    path('', blog_index, name="index-blog"), 
    path('index/', blog_index, name="index-blog"), 
    path('juego_insert', InsertJuego.as_view()) ,
    path('desarrollador_insert', InsertDesarrollador.as_view()) ,
    path('buscarj', BuscarJuego.as_view()),

    path('about/', about, name="index-about"), 

    path('list/', ListNoticia.as_view(), name="list-noticia"),
    path('create/', CreateNoticia.as_view(), name="create-noticia"),
    path('detail/<int:pk>/', DetailNoticia.as_view(), name="detail-noticia"),
    path('update/<int:pk>/', UpdateNoticia.as_view(), name="update-noticia"),
    path('delete/<int:pk>', DeleteNoticia.as_view(), name="delete-noticia"),
    path('search-by-name-/', SearchNoticiaByName.as_view(), name="search-by-name-noticia"),
    path('login/', BlogLogin.as_view(), name="blog-login"),
    path('logout/', BlogLogout.as_view(), name="blog-logout"),    
    path('signup/', BlogSignUp.as_view(), name="blog-signup"),
    path('user-profile/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ejemplo.views import (index, index_tres, imc, monstrar_familiares
                            ,BuscarFamiliar, AltaFamiliar, FamiliarList, FamiliarCrear, FamiliarBorrar, FamiliarActualizar)
from blog.views import index as blog_index                           
from blog.views import InsertJuego, InsertDesarrollador, InsertNoticias, BuscarJuego

urlpatterns = [
    path('admin/', admin.site.urls),
    path('saludar/', index), # ESTA ES LA NUEVA FUNCTION
    path('mostrar-notas/', index_tres), 
    path('imc/<peso>/<altura>/', imc), 
    path('mi-familia/', monstrar_familiares), 
    path('mi-familia/buscar', BuscarFamiliar.as_view()), # clase 20 form
    path('mi-familia/alta', AltaFamiliar.as_view()), # clase 21
    path('panel-familia/', FamiliarList.as_view(), name="familiar-list"), #clase 22
    path('panel-familia/crear', FamiliarCrear.as_view(), name="familiar-crear"), #clase 22
    path('panel-familia/<int:pk>/borrar', FamiliarBorrar.as_view(), name="familiar-borrar"), #clase 22
    path('panel-familia/<int:pk>/actualizar', FamiliarActualizar.as_view(), name="familiar-actualizar"),

    #BLOG - PROYECTO FINAL
    path('blog/', include('blog.urls')),
    
]

#if not settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

class Configuracion(models.Model):
    nombre_blog = models.CharField(max_length=14, default='')
    construido_por = models.CharField(max_length=30, default='')
    titulo_principal = models.CharField(max_length=30, default='')
    subtitulo_principal = models.CharField(max_length=60, default='')

class Juego(models.Model):
    nombre_juego = models.CharField(max_length=50, default='')
    desarrollador = models.CharField(max_length=50, default='')
    genero = models.CharField(max_length=50, default='')
    cantidad_jugadores = models.CharField(max_length=30, default='')
    resena = models.TextField(max_length=3000, default='')

class Desarrollador(models.Model):
    nombre_desarrollador = models.CharField(max_length=50, default='')
    pais = models.CharField(max_length=30, default='')
    anno_fundacion = models.CharField(max_length=30, default='')

class Noticias(models.Model):
    titulo = models.CharField(max_length=100, default='')
    sub_titulo = models.CharField(max_length=255, default='')
    contenido = models.TextField(max_length=3000, default='')
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to="noticias", null=True, blank=True)

    def __str__(self):
        return f"id:{self.id}, title:{self.titulo}"

blog/forms.py
from django import forms
from blog.models import Juego, Desarrollador, Noticias

class BuscarJ(forms.Form):
  nombre_juego = forms.CharField(max_length=30)

class JuegoForm(forms.ModelForm):
  class Meta:
    model = Juego
    fields = ['nombre_juego', 'desarrollador', 'genero', 'cantidad_jugadores', 'resena']

class DesarrolladorForm(forms.ModelForm):
  class Meta:
    model = Desarrollador
    fields = ['nombre_desarrollador', 'pais', 'anno_fundacion']

class NoticiasForm(forms.ModelForm):
  class Meta:
    model = Noticias
    fields = ['titulo', 'sub_titulo', 'contenido']    

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.admin import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View 
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from blog.models import Configuracion, Juego, Desarrollador, Noticias
from blog.forms import BuscarJ ,JuegoForm, DesarrolladorForm, NoticiasForm


#@login_required
def index(request):
    configuracion = Configuracion.objects.first()
    ultimo_juego = Juego.objects.last()
    ultima_noticia = Noticias.objects.last()
    noticias = Noticias.objects.order_by('-fecha').all()
    return render(request, 'blog/index.html', {'configuracion': configuracion
                                                ,'ultimo_juego': ultimo_juego
                                                ,'ultima_noticia': ultima_noticia
                                                ,'Noticias': noticias})

def about(request):
    configuracion = Configuracion.objects.first()
    ultimo_juego = Juego.objects.last()
    return render(request, 'blog/about.html', {'configuracion': configuracion
                                                ,'ultimo_juego': ultimo_juego} )                                                

class InsertJuego(LoginRequiredMixin, View):

    form_class = JuegoForm
    template_name = 'blog/juego_insert.html'
    initial = {"nombre_juego":"", "desarrollador":"", "genero":"", "cantidad_jugadores":"", "resena":""}

    def get(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form
                                                    ,'configuracion': configuracion
                                                    ,'ultimo_juego': ultimo_juego})

    def post(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"Se ingresó con éxito el Juego: {form.cleaned_data.get('nombre_juego')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form 
                                                        ,'msg_exito': msg_exito
                                                        ,'configuracion': configuracion
                                                        ,'ultimo_juego': ultimo_juego})
        
        return render(request, self.template_name, {"form": form})

class InsertDesarrollador(LoginRequiredMixin, View):

    form_class = DesarrolladorForm
    template_name = 'blog/desarrollador_insert.html'
    initial = {"nombre_desarrollador":"", "pais":"", "anno_fundacion":""}

    def get(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form
                                                    ,'configuracion': configuracion
                                                    ,'ultimo_juego': ultimo_juego})

    def post(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"Se ingresó con éxito el Desarrollador: {form.cleaned_data.get('nombre_desarrollador')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form 
                                                        ,'msg_exito': msg_exito
                                                        ,'configuracion': configuracion
                                                        ,'ultimo_juego': ultimo_juego})
        
        return render(request, self.template_name, {"form": form})

class InsertNoticias(LoginRequiredMixin, View):
    
    form_class = NoticiasForm
    template_name = 'blog/noticias_insert.html'
    initial = {"titulo":"", "sub_titulo":"", "contenido":""}

    def get(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form
                                                    ,'configuracion': configuracion
                                                    ,'ultimo_juego': ultimo_juego})

    def post(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"Se ingresó con éxito la Noticia: {form.cleaned_data.get('titulo')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form 
                                                        ,'msg_exito': msg_exito
                                                        ,'configuracion': configuracion
                                                        ,'ultimo_juego': ultimo_juego})
        
        return render(request, self.template_name, {"form": form})        


class BuscarJuego(View):

    form_class = BuscarJ
    template_name = 'blog/buscarj.html'
    initial = {"nombre_juego":""}

    def get(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()       

        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form
                                                    ,'configuracion': configuracion
                                                    ,'ultimo_juego': ultimo_juego})

    def post(self, request):
        configuracion = Configuracion.objects.first()
        ultimo_juego = Juego.objects.last()

        form = self.form_class(request.POST)
        if form.is_valid():
            nombre_juego = form.cleaned_data.get("nombre_juego")
            lista_juegos = Juego.objects.filter(nombre_juego__icontains=nombre_juego).all() 
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form
                                                        ,'lista_juegos':lista_juegos
                                                        ,'configuracion': configuracion
                                                        ,'ultimo_juego': ultimo_juego})

        return render(request, self.template_name, {"form": form})          

##V2 CON GENERIC VIEWS

##Contexto base para heredar en vistas
class CommonMixinExample(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['configuracion'] = Configuracion.objects.first()
        context['ultimo_juego'] = Juego.objects.last()
        return context

class ListNoticia(CommonMixinExample, ListView):
    model = Noticias    

class CreateNoticia(LoginRequiredMixin, CommonMixinExample, CreateView):
    model = Noticias
    fields = ['titulo', 'sub_titulo', 'contenido', 'imagen']
    success_url = reverse_lazy("list-noticia")

class DetailNoticia(CommonMixinExample, DetailView):
    model = Noticias

class UpdateNoticia(LoginRequiredMixin, CommonMixinExample, UpdateView):
    model = Noticias
    fields = ['titulo', 'sub_titulo', 'contenido', 'imagen']
    success_url = reverse_lazy("list-noticia")

class DeleteNoticia(LoginRequiredMixin, CommonMixinExample, DeleteView):
    model = Noticias
    success_url = reverse_lazy("list-noticia")

class SearchNoticiaByName(CommonMixinExample, ListView):
    def get_queryset(self):
        blog_titulo = self.request.GET.get('titulo')
        return Noticias.objects.filter(titulo__icontains=blog_titulo)     
 
class BlogLogin(CommonMixinExample, LoginView):
    template_name = 'blog/blog_login.html'
    next_page = reverse_lazy("index-blog")

class BlogLogout(CommonMixinExample, LogoutView):
    template_name = 'blog/blog_logout.html'     

class BlogSignUp(LoginRequiredMixin, CommonMixinExample, CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("blog-login")
    template_name = "registration/signup.html"

class ProfileUpdate(LoginRequiredMixin, CommonMixinExample, UpdateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy("index-blog")    
    template_name = 'blog/user_form.html'   

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img height="200" class="card-img-top" src="../../static/banner.png" alt="..." /></a>
                        <div class="card-body">

                            <h2 class="card-title">Sobre el blog:</h2>
                            <p class="card-text">Descripción: blog de video juegos, utilizando Python y Django.</p>
                            <p class="card-text">Este blog fue desarrollado por: Erwin Orellana, en Curso de Python (Coderhouse)</p>
                            <p class="card-text">Noviembre, 2022.</p>

                        </div>
                    </div>
             
                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    <style>
        .dropdown {
        display: inline-block;
        position: relative;
        }

        .dropdown-options {
        display: none;
        position: absolute;
        overflow: auto;
        }

        .dropdown:hover .dropdown-options {
        display: block;
        }
    </style>
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Gamer - Reseñas y Noticias de Videojuegos</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/blog">{{configuracion.nombre_blog}}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="/blog">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'index-about' %}">About</a></li>
                        <!--<li class="nav-item"><a class="nav-link" href="/blog/login">Usuario</a></li>-->
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/blog">Blog</a></li>
                    </ul>
                </div>

                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle">Usuario</button>
                    <div class="dropdown-options" >
                      <ul class="">
                        {% if user.is_authenticated %}
                        <a class="btn btn-secondary" href="{% url 'blog-signup' %}">Registro</a>
                        <a class="btn btn-secondary"  href="{% url 'profile-update' user.id %}">Actualizar</a>
                        <a class="btn btn-secondary"  href="{% url 'blog-logout' %}">Salir</a>
                        {% else %}
                        <a class="btn btn-secondary" href="{% url 'blog-login' %}">Ingreso</a>
                        {% endif %}
                      </ul>
                    </div>
                  </div>
                  
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">{{configuracion.titulo_principal}}</h1>
                    <p class="lead mb-0">{{configuracion.subtitulo_principal}}</p>
                </div>
            </div>
        </header>


        <!-- Page content-->
        {% block contenido %}
        {% endblock %}

                <!-- Side widgets-->
                <div class="col-lg-4">

                    <!-- Search widget 2-->
                    <div class="card mb-4">
                        <div class="card-header">Buscar noticia</div>
                        <div class="card-body">
                            <div class="input-group">

                                <form action="{% url 'search-by-name-noticia' %}" method="get">
                                {% csrf_token %}
                                <input class="form-control" type="text" placeholder="Título de noticia..." aria-label="Título de noticia..." aria-describedby="button-search" 
                                name="titulo" maxlength="100" required id="id_titulo"/>
                                <br>
                                <button class="btn btn-primary" id="button-search" type="submit">Buscar!</button>
                                </form>

                            </div>
                        </div>
                    </div>

                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Buscar juego</div>
                        <div class="card-body">
                            <div class="input-group">

                                <form action="/blog/buscarj" method="post">
                                {% csrf_token %}
                                <input class="form-control" type="text" placeholder="Nombre de juego..." aria-label="Nombre de juego..." aria-describedby="button-search" 
                                name="nombre_juego" maxlength="30" required id="id_nombre_juego"/>
                                <br>
                                <button class="btn btn-primary" id="button-search" type="submit">Buscar!</button>
                                </form>

                            </div>
                        </div>
                    </div>

                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Último juego ingresado</div>
                        <div class="card-body">{{ultimo_juego.nombre_juego}}</div>
                    </div>
                    
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Menú de contenido:</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <b><h5>Noticias:</h5></b>
                                        {% if user.is_authenticated %}
                                        <li><a href="{% url 'create-noticia'%}">Ingresar Noticia</a></li>
                                        <li><a href="{% url 'list-noticia'%}">Listar Noticias</a></li>
                                        {% else %}
                                        <li><a href="{% url 'list-noticia'%}">Listar Noticias</a></li>
                                        {% endif %}                                        
                                    </ul>  
                                    <br>                                  
                                    <ul class="list-unstyled mb-0">
                                        {% if user.is_authenticated %}
                                        <b><h5>Otros:</h5></b>
                                        <li><a href="/blog/juego_insert">Ingresar juego</a></li>
                                        <li><a href="/blog/desarrollador_insert">Ingresar desarrollador</a></li>     
                                        {% endif %}                                     
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!"></a></li>
                                        <li><a href="#!"></a></li>
                                        <li><a href="#!"></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Desarrollado por &copy; {{configuracion.construido_por}}</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <!--<script src="js/scripts.js"></script>-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>

    </body>
</html>

blog/templates/blog/blog_login.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img height="200" class="card-img-top" src="../../static/banner.png" alt="..." /></a>
                        <div class="card-body">
                       
                            <h1>Login del Blog</h1>

                            <form method="POST">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button class="btn btn-primary" type="submit">Login</button>
                            </form>
                            <!-- <a href="">create an account</a> -->

                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}

blog/templates/blog/blog_logout.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img height="200" class="card-img-top" src="../../static/banner.png" alt="..." /></a>
                        <div class="card-body">
                       
                            <h1>Ha cerrado sesión.</h1>

                            <a class="btn-primary" href="{% url 'index-blog' %}">ir al index</a>

                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}

blog/templates/blog/buscarj.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <!--<a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..." /></a>-->
                        <div class="card-body">
                            <div class="small text-muted">Resultado de busqueda:</div>
                            {% for juego in lista_juegos %}
                            <h2 class="card-title">Reseña de: {{juego.nombre_juego}}</h2>
                            {% endfor %}
                            
                            {% for juego in lista_juegos %}
                            <ul>
                                <li> Nombre: {{juego.nombre_juego}} </li>
                                <li> Desarrollador: {{juego.desarrollador}} </li>
                                <li> Género: {{juego.genero}} </li>
                                <li> Cant. Jugadores: {{juego.cantidad_jugadores}} </li>
                                <li> Reseña: {{juego.resena}} </li>
                            </ul>
                            {% endfor %}

                            <!--<a class="btn btn-primary" href="#!">Read more →</a>-->
                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}

 

blog/templates/blog/desarrollador_insert.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <!--<a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..." /></a>-->
                        <div class="card-body">
                            <div class="small text-muted">Nuevo desarrollador:</div>
                            <h2 class="card-title">Ingrese el nuevo Desarrollador</h2>
                            
                            <!--Formulario-->
                            <form action="/blog/desarrollador_insert" method="post">
                                <br>
                                {% csrf_token %} 
                                {{ form.as_p}}
                                <input type="submit" value="Ingresar" class="btn btn-primary" >
                            </form>
                            
                            <br>
                            <h2 style="color:green">{{msg_exito}}</h2>

                            <!--<a class="btn btn-primary" href="#!">Read more →</a>-->
                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="{{ ultima_noticia.imagen.url }}" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">{{ultima_noticia.fecha}}</div>
                            <h2 class="card-title">{{ultima_noticia.titulo}}</h2>
                            <p class="card-text">{{ultima_noticia.sub_titulo}}</p>
                            <a class="btn btn-primary" href="{% url 'detail-noticia' ultima_noticia.id %}">Leer noticia →</a>
                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>


{% endblock %}

 

blog/templates/blog/juego_insert.html
{% extends 'blog/base.html' %}

{% block contenido %}

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <!--<a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..." /></a>-->
                        <div class="card-body">
                            <div class="small text-muted">Nueva reseña:</div>
                            <h2 class="card-title">Ingrese el nuevo Juego</h2>
                            
                            <!--Formulario-->
                            <form action="/blog/juego_insert" method="post">
                                <br>
                                {% csrf_token %} 
                                {{ form.as_p}}
                                <input type="submit" value="Ingresar" class="btn btn-primary" >
                            </form>
                            
                            <br>
                            <h2 style="color:green">{{msg_exito}}</h2>

                            <!--<a class="btn btn-primary" href="#!">Read more →</a>-->
                        </div>
                    </div>

                    <!-- Nested row for non-featured blog posts-->
                                    
                </div>

{% endblock %}